In [ ]:
from bs4 import BeautifulSoup
import requests
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
import pandas as pd
import numpy as np
import re

In [ ]:
URL = "https://racing.hkjc.com/racing/information/English/Jockey/JockeyRanking.aspx?Season=Previous&View=Numbers&Racecourse=ALL"
driver = webdriver.Chrome(executable_path='/Applications/chromedriver')
driver.get(URL)
#df=pd.DataFrame()

wait=WebDriverWait(driver,10) #sometimes takes time for the page to load

subhtml = driver.page_source
soup3 = BeautifulSoup(subhtml, "html.parser")

In [ ]:
table = soup3.find_all(class_="table_bd")
table_data = [i.find_all('td') for i in table]
l = [i.text.strip() for i in table_data[0]]

In [ ]:
jockeys=[]
for i in range(int(len(l[2:])/8)):
    jockeys.append(l[2+8*i:2+8*i+8])
    print(jockeys)

[['Jockey', 'Win', '2nd', '3rd', '4th', '5th', 'Total Rides', 'Stakes Won']]
[['Jockey', 'Win', '2nd', '3rd', '4th', '5th', 'Total Rides', 'Stakes Won'], ['Z Purton', '147', '101', '100', '56', '66', '707', '$202,112,646']]
[['Jockey', 'Win', '2nd', '3rd', '4th', '5th', 'Total Rides', 'Stakes Won'], ['Z Purton', '147', '101', '100', '56', '66', '707', '$202,112,646'], ['J Moreira', '138', '123', '91', '68', '66', '719', '$206,911,366']]
[['Jockey', 'Win', '2nd', '3rd', '4th', '5th', 'Total Rides', 'Stakes Won'], ['Z Purton', '147', '101', '100', '56', '66', '707', '$202,112,646'], ['J Moreira', '138', '123', '91', '68', '66', '719', '$206,911,366'], ['K Teetan', '93', '75', '81', '81', '72', '719', '$138,503,489']]
[['Jockey', 'Win', '2nd', '3rd', '4th', '5th', 'Total Rides', 'Stakes Won'], ['Z Purton', '147', '101', '100', '56', '66', '707', '$202,112,646'], ['J Moreira', '138', '123', '91', '68', '66', '719', '$206,911,366'], ['K Teetan', '93', '75', '81', '81', '72', '719', '$138,503,489'], ['C Y Ho', '67', '60', '58', '62', '71', '623', '$126,366,677']]
[['Jockey', 'Win', '2nd', '3rd', '4th', '5th', 'Total Rides', 'Stakes Won'], ['Z Purton', '147', '101', '100', '56', '66', '707', '$202,112,646'], ['J Moreira', '138', '123', '91', '68', '66', '719', '$206,911,366'], ['K Teetan', '93', '75', '81', '81', '72', '719', '$138,503,489'], ['C Y Ho', '67', '60', '58', '62', '71', '623', '$126,366,677'], ['C Schofield', '43', '40', '40', '41', '48', '491', '$54,304,475']]
[['Jockey', 'Win', '2nd', '3rd', '4th', '5th', 'Total Rides', 'Stakes Won'], ['Z Purton', '147', '101', '100', '56', '66', '707', '$202,112,646'], ['J Moreira', '138', '123', '91', '68', '66', '719', '$206,911,366'], ['K Teetan', '93', '75', '81', '81', '72', '719', '$138,503,489'], ['C Y Ho', '67', '60', '58', '62', '71', '623', '$126,366,677'], ['C Schofield', '43', '40', '40', '41', '48', '491', '$54,304,475'], ['G van Niekerk', '37', '44', '40', '40', '30', '350', '$56,048,185']]
[['Jockey', 'Win', '2nd', '3rd', '4th', '5th', 'Total Rides', 'Stakes Won'], ['Z Purton', '147', '101', '100', '56', '66', '707', '$202,112,646'], ['J Moreira', '138', '123', '91', '68', '66', '719', '$206,911,366'], ['K Teetan', '93', '75', '81', '81', '72', '719', '$138,503,489'], ['C Y Ho', '67', '60', '58', '62', '71', '623', '$126,366,677'], ['C Schofield', '43', '40', '40', '41', '48', '491', '$54,304,475'], ['G van Niekerk', '37', '44', '40', '40', '30', '350', '$56,048,185'], ['M F Poon', '29', '23', '36', '47', '50', '555', '$39,061,505']]
[['Jockey', 'Win', '2nd', '3rd', '4th', '5th', 'Total Rides', 'Stakes Won'], ['Z Purton', '147', '101', '100', '56', '66', '707', '$202,112,646'], ['J Moreira', '138', '123', '91', '68', '66', '719', '$206,911,366'], ['K Teetan', '93', '75', '81', '81', '72', '719', '$138,503,489'], ['C Y Ho', '67', '60', '58', '62', '71', '623', '$126,366,677'], ['C Schofield', '43', '40', '40', '41', '48', '491', '$54,304,475'], ['G van Niekerk', '37', '44', '40', '40', '30', '350', '$56,048,185'], ['M F Poon', '29', '23', '36', '47', '50', '555', '$39,061,505'], ['K C Leung', '29', '21', '36', '50', '54', '562', '$37,146,565']]
[['Jockey', 'Win', '2nd', '3rd', '4th', '5th', 'Total Rides', 'Stakes Won'], ['Z Purton', '147', '101', '100', '56', '66', '707', '$202,112,646'], ['J Moreira', '138', '123', '91', '68', '66', '719', '$206,911,366'], ['K Teetan', '93', '75', '81', '81', '72', '719', '$138,503,489'], ['C Y Ho', '67', '60', '58', '62', '71', '623', '$126,366,677'], ['C Schofield', '43', '40', '40', '41', '48', '491', '$54,304,475'], ['G van Niekerk', '37', '44', '40', '40', '30', '350', '$56,048,185'], ['M F Poon', '29', '23', '36', '47', '50', '555', '$39,061,505'], ['K C Leung', '29', '21', '36', '50', '54', '562', '$37,146,565'], ['N Callan', '26', '40', '40', '58', '44', '481', '$42,185,220']]
[['Jockey', 'Win', '2nd', '3rd', '4th', '5th', 'Total Rides', 'Stakes Won'], ['Z Purton', '147', '101', '100', '56', '66', '707', '$202,112,646'], ['J Moreira', '138', '123', '91', '68', '66', '719', '$206,911,366'], ['K Teetan', '93', '75', '81', '81', '72', '719', '$138,503,489'], ['C Y Ho', '67', '60', '58', '62', '71', '623', '$126,366,677'], ['C Schofield', '43', '40', '40', '41', '48', '491', '$54,304,475'], ['G van Niekerk', '37', '44', '40', '40', '30', '350', '$56,048,185'], ['M F Poon', '29', '23', '36', '47', '50', '555', '$39,061,505'], ['K C Leung', '29', '21', '36', '50', '54', '562', '$37,146,565'], ['N Callan', '26', '40', '40', '58', '44', '481', '$42,185,220'], ['A Badel', '26', '23', '21', '23', '16', '254', '$33,166,408']]
[['Jockey', 'Win', '2nd', '3rd', '4th', '5th', 'Total Rides', 'Stakes Won'], ['Z Purton', '147', '101', '100', '56', '66', '707', '$202,112,646'], ['J Moreira', '138', '123', '91', '68', '66', '719', '$206,911,366'], ['K Teetan', '93', '75', '81', '81', '72', '719', '$138,503,489'], ['C Y Ho', '67', '60', '58', '62', '71', '623', '$126,366,677'], ['C Schofield', '43', '40', '40', '41', '48', '491', '$54,304,475'], ['G van Niekerk', '37', '44', '40', '40', '30', '350', '$56,048,185'], ['M F Poon', '29', '23', '36', '47', '50', '555', '$39,061,505'], ['K C Leung', '29', '21', '36', '50', '54', '562', '$37,146,565'], ['N Callan', '26', '40', '40', '58', '44', '481', '$42,185,220'], ['A Badel', '26', '23', '21', '23', '16', '254', '$33,166,408'], ['M Chadwick', '24', '41', '42', '33', '44', '510', '$48,535,923']]
[['Jockey', 'Win', '2nd', '3rd', '4th', '5th', 'Total Rides', 'Stakes Won'], ['Z Purton', '147', '101', '100', '56', '66', '707', '$202,112,646'], ['J Moreira', '138', '123', '91', '68', '66', '719', '$206,911,366'], ['K Teetan', '93', '75', '81', '81', '72', '719', '$138,503,489'], ['C Y Ho', '67', '60', '58', '62', '71', '623', '$126,366,677'], ['C Schofield', '43', '40', '40', '41', '48', '491', '$54,304,475'], ['G van Niekerk', '37', '44', '40', '40', '30', '350', '$56,048,185'], ['M F Poon', '29', '23', '36', '47', '50', '555', '$39,061,505'], ['K C Leung', '29', '21', '36', '50', '54', '562', '$37,146,565'], ['N Callan', '26', '40', '40', '58', '44', '481', '$42,185,220'], ['A Badel', '26', '23', '21', '23', '16', '254', '$33,166,408'], ['M Chadwick', '24', '41', '42', '33', '44', '510', '$48,535,923'], ['K H Chan', '22', '20', '28', '25', '18', '312', '$28,282,138']]
[['Jockey', 'Win', '2nd', '3rd', '4th', '5th', 'Total Rides', 'Stakes Won'], ['Z Purton', '147', '101', '100', '56', '66', '707', '$202,112,646'], ['J Moreira', '138', '123', '91', '68', '66', '719', '$206,911,366'], ['K Teetan', '93', '75', '81', '81', '72', '719', '$138,503,489'], ['C Y Ho', '67', '60', '58', '62', '71', '623', '$126,366,677'], ['C Schofield', '43', '40', '40', '41', '48', '491', '$54,304,475'], ['G van Niekerk', '37', '44', '40', '40', '30', '350', '$56,048,185'], ['M F Poon', '29', '23', '36', '47', '50', '555', '$39,061,505'], ['K C Leung', '29', '21', '36', '50', '54', '562', '$37,146,565'], ['N Callan', '26', '40', '40', '58', '44', '481', '$42,185,220'], ['A Badel', '26', '23', '21', '23', '16', '254', '$33,166,408'], ['M Chadwick', '24', '41', '42', '33', '44', '510', '$48,535,923'], ['K H Chan', '22', '20', '28', '25', '18', '312', '$28,282,138'], ['A Hamelin', '17', '17', '16', '24', '24', '227', '$21,594,370']]
[['Jockey', 'Win', '2nd', '3rd', '4th', '5th', 'Total Rides', 'Stakes Won'], ['Z Purton', '147', '101', '100', '56', '66', '707', '$202,112,646'], ['J Moreira', '138', '123', '91', '68', '66', '719', '$206,911,366'], ['K Teetan', '93', '75', '81', '81', '72', '719', '$138,503,489'], ['C Y Ho', '67', '60', '58', '62', '71', '623', '$126,366,677'], ['C Schofield', '43', '40', '40', '41', '48', '491', '$54,304,475'], ['G van Niekerk', '37', '44', '40', '40', '30', '350', '$56,048,185'], ['M F Poon', '29', '23', '36', '47', '50', '555', '$39,061,505'], ['K C Leung', '29', '21', '36', '50', '54', '562', '$37,146,565'], ['N Callan', '26', '40', '40', '58', '44', '481', '$42,185,220'], ['A Badel', '26', '23', '21', '23', '16', '254', '$33,166,408'], ['M Chadwick', '24', '41', '42', '33', '44', '510', '$48,535,923'], ['K H Chan', '22', '20', '28', '25', '18', '312', '$28,282,138'], ['A Hamelin', '17', '17', '16', '24', '24', '227', '$21,594,370'], ['V Borges', '16', '18', '17', '16', '21', '242', '$21,600,335']]
[['Jockey', 'Win', '2nd', '3rd', '4th', '5th', 'Total Rides', 'Stakes Won'], ['Z Purton', '147', '101', '100', '56', '66', '707', '$202,112,646'], ['J Moreira', '138', '123', '91', '68', '66', '719', '$206,911,366'], ['K Teetan', '93', '75', '81', '81', '72', '719', '$138,503,489'], ['C Y Ho', '67', '60', '58', '62', '71', '623', '$126,366,677'], ['C Schofield', '43', '40', '40', '41', '48', '491', '$54,304,475'], ['G van Niekerk', '37', '44', '40', '40', '30', '350', '$56,048,185'], ['M F Poon', '29', '23', '36', '47', '50', '555', '$39,061,505'], ['K C Leung', '29', '21', '36', '50', '54', '562', '$37,146,565'], ['N Callan', '26', '40', '40', '58', '44', '481', '$42,185,220'], ['A Badel', '26', '23', '21', '23', '16', '254', '$33,166,408'], ['M Chadwick', '24', '41', '42', '33', '44', '510', '$48,535,923'], ['K H Chan', '22', '20', '28', '25', '18', '312', '$28,282,138'], ['A Hamelin', '17', '17', '16', '24', '24', '227', '$21,594,370'], ['V Borges', '16', '18', '17', '16', '21', '242', '$21,600,335'], ['B Shinn', '15', '43', '38', '34', '36', '445', '$38,044,770']]
[['Jockey', 'Win', '2nd', '3rd', '4th', '5th', 'Total Rides', 'Stakes Won'], ['Z Purton', '147', '101', '100', '56', '66', '707', '$202,112,646'], ['J Moreira', '138', '123', '91', '68', '66', '719', '$206,911,366'], ['K Teetan', '93', '75', '81', '81', '72', '719', '$138,503,489'], ['C Y Ho', '67', '60', '58', '62', '71', '623', '$126,366,677'], ['C Schofield', '43', '40', '40', '41', '48', '491', '$54,304,475'], ['G van Niekerk', '37', '44', '40', '40', '30', '350', '$56,048,185'], ['M F Poon', '29', '23', '36', '47', '50', '555', '$39,061,505'], ['K C Leung', '29', '21', '36', '50', '54', '562', '$37,146,565'], ['N Callan', '26', '40', '40', '58', '44', '481', '$42,185,220'], ['A Badel', '26', '23', '21', '23', '16', '254', '$33,166,408'], ['M Chadwick', '24', '41', '42', '33', '44', '510', '$48,535,923'], ['K H Chan', '22', '20', '28', '25', '18', '312', '$28,282,138'], ['A Hamelin', '17', '17', '16', '24', '24', '227', '$21,594,370'], ['V Borges', '16', '18', '17', '16', '21', '242', '$21,600,335'], ['B Shinn', '15', '43', '38', '34', '36', '445', '$38,044,770'], ['S de Sousa', '14', '13', '12', '15', '17', '149', '$18,063,749']]
[['Jockey', 'Win', '2nd', '3rd', '4th', '5th', 'Total Rides', 'Stakes Won'], ['Z Purton', '147', '101', '100', '56', '66', '707', '$202,112,646'], ['J Moreira', '138', '123', '91', '68', '66', '719', '$206,911,366'], ['K Teetan', '93', '75', '81', '81', '72', '719', '$138,503,489'], ['C Y Ho', '67', '60', '58', '62', '71', '623', '$126,366,677'], ['C Schofield', '43', '40', '40', '41', '48', '491', '$54,304,475'], ['G van Niekerk', '37', '44', '40', '40', '30', '350', '$56,048,185'], ['M F Poon', '29', '23', '36', '47', '50', '555', '$39,061,505'], ['K C Leung', '29', '21', '36', '50', '54', '562', '$37,146,565'], ['N Callan', '26', '40', '40', '58', '44', '481', '$42,185,220'], ['A Badel', '26', '23', '21', '23', '16', '254', '$33,166,408'], ['M Chadwick', '24', '41', '42', '33', '44', '510', '$48,535,923'], ['K H Chan', '22', '20', '28', '25', '18', '312', '$28,282,138'], ['A Hamelin', '17', '17', '16', '24', '24', '227', '$21,594,370'], ['V Borges', '16', '18', '17', '16', '21', '242', '$21,600,335'], ['B Shinn', '15', '43', '38', '34', '36', '445', '$38,044,770'], ['S de Sousa', '14', '13', '12', '15', '17', '149', '$18,063,749'], ['H T Mo', '12', '18', '12', '12', '21', '350', '$16,507,705']]
[['Jockey', 'Win', '2nd', '3rd', '4th', '5th', 'Total Rides', 'Stakes Won'], ['Z Purton', '147', '101', '100', '56', '66', '707', '$202,112,646'], ['J Moreira', '138', '123', '91', '68', '66', '719', '$206,911,366'], ['K Teetan', '93', '75', '81', '81', '72', '719', '$138,503,489'], ['C Y Ho', '67', '60', '58', '62', '71', '623', '$126,366,677'], ['C Schofield', '43', '40', '40', '41', '48', '491', '$54,304,475'], ['G van Niekerk', '37', '44', '40', '40', '30', '350', '$56,048,185'], ['M F Poon', '29', '23', '36', '47', '50', '555', '$39,061,505'], ['K C Leung', '29', '21', '36', '50', '54', '562', '$37,146,565'], ['N Callan', '26', '40', '40', '58', '44', '481', '$42,185,220'], ['A Badel', '26', '23', '21', '23', '16', '254', '$33,166,408'], ['M Chadwick', '24', '41', '42', '33', '44', '510', '$48,535,923'], ['K H Chan', '22', '20', '28', '25', '18', '312', '$28,282,138'], ['A Hamelin', '17', '17', '16', '24', '24', '227', '$21,594,370'], ['V Borges', '16', '18', '17', '16', '21', '242', '$21,600,335'], ['B Shinn', '15', '43', '38', '34', '36', '445', '$38,044,770'], ['S de Sousa', '14', '13', '12', '15', '17', '149', '$18,063,749'], ['H T Mo', '12', '18', '12', '12', '21', '350', '$16,507,705'], ['C Wong', '9', '7', '8', '14', '6', '190', '$9,261,815']]
[['Jockey', 'Win', '2nd', '3rd', '4th', '5th', 'Total Rides', 'Stakes Won'], ['Z Purton', '147', '101', '100', '56', '66', '707', '$202,112,646'], ['J Moreira', '138', '123', '91', '68', '66', '719', '$206,911,366'], ['K Teetan', '93', '75', '81', '81', '72', '719', '$138,503,489'], ['C Y Ho', '67', '60', '58', '62', '71', '623', '$126,366,677'], ['C Schofield', '43', '40', '40', '41', '48', '491', '$54,304,475'], ['G van Niekerk', '37', '44', '40', '40', '30', '350', '$56,048,185'], ['M F Poon', '29', '23', '36', '47', '50', '555', '$39,061,505'], ['K C Leung', '29', '21', '36', '50', '54', '562', '$37,146,565'], ['N Callan', '26', '40', '40', '58', '44', '481', '$42,185,220'], ['A Badel', '26', '23', '21', '23', '16', '254', '$33,166,408'], ['M Chadwick', '24', '41', '42', '33', '44', '510', '$48,535,923'], ['K H Chan', '22', '20', '28', '25', '18', '312', '$28,282,138'], ['A Hamelin', '17', '17', '16', '24', '24', '227', '$21,594,370'], ['V Borges', '16', '18', '17', '16', '21', '242', '$21,600,335'], ['B Shinn', '15', '43', '38', '34', '36', '445', '$38,044,770'], ['S de Sousa', '14', '13', '12', '15', '17', '149', '$18,063,749'], ['H T Mo', '12', '18', '12', '12', '21', '350', '$16,507,705'], ['C Wong', '9', '7', '8', '14', '6', '190', '$9,261,815'], ['A Sanna', '9', '4', '9', '7', '10', '120', '$10,735,300']]
[['Jockey', 'Win', '2nd', '3rd', '4th', '5th', 'Total Rides', 'Stakes Won'], ['Z Purton', '147', '101', '100', '56', '66', '707', '$202,112,646'], ['J Moreira', '138', '123', '91', '68', '66', '719', '$206,911,366'], ['K Teetan', '93', '75', '81', '81', '72', '719', '$138,503,489'], ['C Y Ho', '67', '60', '58', '62', '71', '623', '$126,366,677'], ['C Schofield', '43', '40', '40', '41', '48', '491', '$54,304,475'], ['G van Niekerk', '37', '44', '40', '40', '30', '350', '$56,048,185'], ['M F Poon', '29', '23', '36', '47', '50', '555', '$39,061,505'], ['K C Leung', '29', '21', '36', '50', '54', '562', '$37,146,565'], ['N Callan', '26', '40', '40', '58', '44', '481', '$42,185,220'], ['A Badel', '26', '23', '21', '23', '16', '254', '$33,166,408'], ['M Chadwick', '24', '41', '42', '33', '44', '510', '$48,535,923'], ['K H Chan', '22', '20', '28', '25', '18', '312', '$28,282,138'], ['A Hamelin', '17', '17', '16', '24', '24', '227', '$21,594,370'], ['V Borges', '16', '18', '17', '16', '21', '242', '$21,600,335'], ['B Shinn', '15', '43', '38', '34', '36', '445', '$38,044,770'], ['S de Sousa', '14', '13', '12', '15', '17', '149', '$18,063,749'], ['H T Mo', '12', '18', '12', '12', '21', '350', '$16,507,705'], ['C Wong', '9', '7', '8', '14', '6', '190', '$9,261,815'], ['A Sanna', '9', '4', '9', '7', '10', '120', '$10,735,300'], ['M L Yeung', '8', '15', '16', '24', '21', '418', '$16,150,280']]
[['Jockey', 'Win', '2nd', '3rd', '4th', '5th', 'Total Rides', 'Stakes Won'], ['Z Purton', '147', '101', '100', '56', '66', '707', '$202,112,646'], ['J Moreira', '138', '123', '91', '68', '66', '719', '$206,911,366'], ['K Teetan', '93', '75', '81', '81', '72', '719', '$138,503,489'], ['C Y Ho', '67', '60', '58', '62', '71', '623', '$126,366,677'], ['C Schofield', '43', '40', '40', '41', '48', '491', '$54,304,475'], ['G van Niekerk', '37', '44', '40', '40', '30', '350', '$56,048,185'], ['M F Poon', '29', '23', '36', '47', '50', '555', '$39,061,505'], ['K C Leung', '29', '21', '36', '50', '54', '562', '$37,146,565'], ['N Callan', '26', '40', '40', '58', '44', '481', '$42,185,220'], ['A Badel', '26', '23', '21', '23', '16', '254', '$33,166,408'], ['M Chadwick', '24', '41', '42', '33', '44', '510', '$48,535,923'], ['K H Chan', '22', '20', '28', '25', '18', '312', '$28,282,138'], ['A Hamelin', '17', '17', '16', '24', '24', '227', '$21,594,370'], ['V Borges', '16', '18', '17', '16', '21', '242', '$21,600,335'], ['B Shinn', '15', '43', '38', '34', '36', '445', '$38,044,770'], ['S de Sousa', '14', '13', '12', '15', '17', '149', '$18,063,749'], ['H T Mo', '12', '18', '12', '12', '21', '350', '$16,507,705'], ['C Wong', '9', '7', '8', '14', '6', '190', '$9,261,815'], ['A Sanna', '9', '4', '9', '7', '10', '120', '$10,735,300'], ['M L Yeung', '8', '15', '16', '24', '21', '418', '$16,150,280'], ['T Piccone', '8', '6', '12', '5', '5', '91', '$9,437,375']]
[['Jockey', 'Win', '2nd', '3rd', '4th', '5th', 'Total Rides', 'Stakes Won'], ['Z Purton', '147', '101', '100', '56', '66', '707', '$202,112,646'], ['J Moreira', '138', '123', '91', '68', '66', '719', '$206,911,366'], ['K Teetan', '93', '75', '81', '81', '72', '719', '$138,503,489'], ['C Y Ho', '67', '60', '58', '62', '71', '623', '$126,366,677'], ['C Schofield', '43', '40', '40', '41', '48', '491', '$54,304,475'], ['G van Niekerk', '37', '44', '40', '40', '30', '350', '$56,048,185'], ['M F Poon', '29', '23', '36', '47', '50', '555', '$39,061,505'], ['K C Leung', '29', '21', '36', '50', '54', '562', '$37,146,565'], ['N Callan', '26', '40', '40', '58', '44', '481', '$42,185,220'], ['A Badel', '26', '23', '21', '23', '16', '254', '$33,166,408'], ['M Chadwick', '24', '41', '42', '33', '44', '510', '$48,535,923'], ['K H Chan', '22', '20', '28', '25', '18', '312', '$28,282,138'], ['A Hamelin', '17', '17', '16', '24', '24', '227', '$21,594,370'], ['V Borges', '16', '18', '17', '16', '21', '242', '$21,600,335'], ['B Shinn', '15', '43', '38', '34', '36', '445', '$38,044,770'], ['S de Sousa', '14', '13', '12', '15', '17', '149', '$18,063,749'], ['H T Mo', '12', '18', '12', '12', '21', '350', '$16,507,705'], ['C Wong', '9', '7', '8', '14', '6', '190', '$9,261,815'], ['A Sanna', '9', '4', '9', '7', '10', '120', '$10,735,300'], ['M L Yeung', '8', '15', '16', '24', '21', '418', '$16,150,280'], ['T Piccone', '8', '6', '12', '5', '5', '91', '$9,437,375'], ['C L Chau', '7', '11', '12', '6', '7', '94', '$11,640,745']]

In [ ]:
jockeys

[['Jockey', 'Win', '2nd', '3rd', '4th', '5th', 'Total Rides', 'Stakes Won'],
 ['Z Purton', '147', '101', '100', '56', '66', '707', '$202,112,646'],
 ['J Moreira', '138', '123', '91', '68', '66', '719', '$206,911,366'],
 ['K Teetan', '93', '75', '81', '81', '72', '719', '$138,503,489'],
 ['C Y Ho', '67', '60', '58', '62', '71', '623', '$126,366,677'],
 ['C Schofield', '43', '40', '40', '41', '48', '491', '$54,304,475'],
 ['G van Niekerk', '37', '44', '40', '40', '30', '350', '$56,048,185'],
 ['M F Poon', '29', '23', '36', '47', '50', '555', '$39,061,505'],
 ['K C Leung', '29', '21', '36', '50', '54', '562', '$37,146,565'],
 ['N Callan', '26', '40', '40', '58', '44', '481', '$42,185,220'],
 ['A Badel', '26', '23', '21', '23', '16', '254', '$33,166,408'],
 ['M Chadwick', '24', '41', '42', '33', '44', '510', '$48,535,923'],
 ['K H Chan', '22', '20', '28', '25', '18', '312', '$28,282,138'],
 ['A Hamelin', '17', '17', '16', '24', '24', '227', '$21,594,370'],
 ['V Borges', '16', '18', '17', '16', '21', '242', '$21,600,335'],
 ['B Shinn', '15', '43', '38', '34', '36', '445', '$38,044,770'],
 ['S de Sousa', '14', '13', '12', '15', '17', '149', '$18,063,749'],
 ['H T Mo', '12', '18', '12', '12', '21', '350', '$16,507,705'],
 ['C Wong', '9', '7', '8', '14', '6', '190', '$9,261,815'],
 ['A Sanna', '9', '4', '9', '7', '10', '120', '$10,735,300'],
 ['M L Yeung', '8', '15', '16', '24', '21', '418', '$16,150,280'],
 ['T Piccone', '8', '6', '12', '5', '5', '91', '$9,437,375'],
 ['C L Chau', '7', '11', '12', '6', '7', '94', '$11,640,745'],
 ['H N Wong', '6', '10', '6', '12', '17', '354', '$8,459,485'],
 ['U Rispoli', '5', '8', '8', '13', '7', '110', '$7,078,860'],
 ['T H So', '4', '10', '13', '10', '18', '320', '$8,847,788'],
 ['H W Lai', '4', '8', '10', '15', '6', '325', '$7,514,865'],
 ['A Domeyer', '4', '6', '11', '2', '7', '52', '$5,972,550'],
 ['L Hewitson', '3', '9', '11', '14', '10', '251', '$7,362,155'],
 ['R Moore', '2', '5', '1', '0', '4', '21', '$12,818,503'],
 ['R Bayliss', '2', '3', '4', '2', '5', '90', '$3,181,375'],
 ['C Soumillon', '1', '1', '0', '1', '0', '4', '$19,620,000'],
 ['M Matsuoka', '1', '0', '0', '0', '0', '1', '$15,960,000'],
 ['C Keane', '1', '0', '0', '0', '0', '4', '$991,800'],
 ['H Bowman', '0', '3', '1', '5', '2', '18', '$5,491,445'],
 ['J McDonald', '0', '2', '0', '2', '0', '13', '$943,420'],
 ['Y Kawada', '0', '1', '0', '1', '0', '4', '$324,912'],
 ['J Spencer', '0', '1', '0', '0', '1', '8', '$2,233,845'],
 ['O Murphy', '0', '0', '1', '3', '2', '11', '$2,393,645'],
 ['D Lane', '0', '0', '0', '1', '0', '3', '$87,000'],
 ['W L Ho', '0', '0', '0', '1', '0', '3', '$195,000'],
 ['C Lemaire', '0', '0', '0', '1', '0', '5', '$1,425,000'],
 ['M Guyon', '0', '0', '0', '0', '2', '3', '$710,750'],
 ['S Pasquier', '0', '0', '0', '0', '1', '1', '$924,000'],
 ['L Dettori', '0', '0', '0', '0', '1', '8', '$40,614'],
 ['B Avdulla', '0', '0', '0', '0', '0', '1', '$0'],
 ['J Watson', '0', '0', '0', '0', '0', '1', '$0'],
 ['K McEvoy', '0', '0', '0', '0', '0', '1', '$0'],
 ['M Walker', '0', '0', '0', '0', '0', '1', '$0'],
 ['W Lordan', '0', '0', '0', '0', '0', '1', '$0'],
 ['P-C Boudot', '0', '0', '0', '0', '0', '4', '$0']]

In [ ]:
jockeyframe=pd.DataFrame(jockeys)

In [ ]:
jockeyframe

                0    1    2    3    4    5            6             7
0          Jockey  Win  2nd  3rd  4th  5th  Total Rides    Stakes Won
1        Z Purton  147  101  100   56   66          707  $202,112,646
2       J Moreira  138  123   91   68   66          719  $206,911,366
3        K Teetan   93   75   81   81   72          719  $138,503,489
4          C Y Ho   67   60   58   62   71          623  $126,366,677
5     C Schofield   43   40   40   41   48          491   $54,304,475
6   G van Niekerk   37   44   40   40   30          350   $56,048,185
7        M F Poon   29   23   36   47   50          555   $39,061,505
8       K C Leung   29   21   36   50   54          562   $37,146,565
9        N Callan   26   40   40   58   44          481   $42,185,220
10        A Badel   26   23   21   23   16          254   $33,166,408
11     M Chadwick   24   41   42   33   44          510   $48,535,923
12       K H Chan   22   20   28   25   18          312   $28,282,138
13      A Hamelin   17   17   16   24   24          227   $21,594,370
14       V Borges   16   18   17   16   21          242   $21,600,335
15        B Shinn   15   43   38   34   36          445   $38,044,770
16     S de Sousa   14   13   12   15   17          149   $18,063,749
17         H T Mo   12   18   12   12   21          350   $16,507,705
18         C Wong    9    7    8   14    6          190    $9,261,815
19        A Sanna    9    4    9    7   10          120   $10,735,300
20      M L Yeung    8   15   16   24   21          418   $16,150,280
21      T Piccone    8    6   12    5    5           91    $9,437,375
22       C L Chau    7   11   12    6    7           94   $11,640,745
23       H N Wong    6   10    6   12   17          354    $8,459,485
24      U Rispoli    5    8    8   13    7          110    $7,078,860
25         T H So    4   10   13   10   18          320    $8,847,788
26        H W Lai    4    8   10   15    6          325    $7,514,865
27      A Domeyer    4    6   11    2    7           52    $5,972,550
28     L Hewitson    3    9   11   14   10          251    $7,362,155
29        R Moore    2    5    1    0    4           21   $12,818,503
30      R Bayliss    2    3    4    2    5           90    $3,181,375
31    C Soumillon    1    1    0    1    0            4   $19,620,000
32     M Matsuoka    1    0    0    0    0            1   $15,960,000
33        C Keane    1    0    0    0    0            4      $991,800
34       H Bowman    0    3    1    5    2           18    $5,491,445
35     J McDonald    0    2    0    2    0           13      $943,420
36       Y Kawada    0    1    0    1    0            4      $324,912
37      J Spencer    0    1    0    0    1            8    $2,233,845
38       O Murphy    0    0    1    3    2           11    $2,393,645
39         D Lane    0    0    0    1    0            3       $87,000
40         W L Ho    0    0    0    1    0            3      $195,000
41      C Lemaire    0    0    0    1    0            5    $1,425,000
42        M Guyon    0    0    0    0    2            3      $710,750
43     S Pasquier    0    0    0    0    1            1      $924,000
44      L Dettori    0    0    0    0    1            8       $40,614
45      B Avdulla    0    0    0    0    0            1            $0
46       J Watson    0    0    0    0    0            1            $0
47       K McEvoy    0    0    0    0    0            1            $0
48       M Walker    0    0    0    0    0            1            $0
49       W Lordan    0    0    0    0    0            1            $0
50     P-C Boudot    0    0    0    0    0            4            $0

In [ ]:
jockeyframe.columns = jockeyframe.iloc[0]

In [ ]:
jockeyframe=jockeyframe.drop(0)

In [ ]:
jockeyframe

0          Jockey  Win  2nd  3rd 4th 5th Total Rides    Stakes Won
1        Z Purton  147  101  100  56  66         707  $202,112,646
2       J Moreira  138  123   91  68  66         719  $206,911,366
3        K Teetan   93   75   81  81  72         719  $138,503,489
4          C Y Ho   67   60   58  62  71         623  $126,366,677
5     C Schofield   43   40   40  41  48         491   $54,304,475
6   G van Niekerk   37   44   40  40  30         350   $56,048,185
7        M F Poon   29   23   36  47  50         555   $39,061,505
8       K C Leung   29   21   36  50  54         562   $37,146,565
9        N Callan   26   40   40  58  44         481   $42,185,220
10        A Badel   26   23   21  23  16         254   $33,166,408
11     M Chadwick   24   41   42  33  44         510   $48,535,923
12       K H Chan   22   20   28  25  18         312   $28,282,138
13      A Hamelin   17   17   16  24  24         227   $21,594,370
14       V Borges   16   18   17  16  21         242   $21,600,335
15        B Shinn   15   43   38  34  36         445   $38,044,770
16     S de Sousa   14   13   12  15  17         149   $18,063,749
17         H T Mo   12   18   12  12  21         350   $16,507,705
18         C Wong    9    7    8  14   6         190    $9,261,815
19        A Sanna    9    4    9   7  10         120   $10,735,300
20      M L Yeung    8   15   16  24  21         418   $16,150,280
21      T Piccone    8    6   12   5   5          91    $9,437,375
22       C L Chau    7   11   12   6   7          94   $11,640,745
23       H N Wong    6   10    6  12  17         354    $8,459,485
24      U Rispoli    5    8    8  13   7         110    $7,078,860
25         T H So    4   10   13  10  18         320    $8,847,788
26        H W Lai    4    8   10  15   6         325    $7,514,865
27      A Domeyer    4    6   11   2   7          52    $5,972,550
28     L Hewitson    3    9   11  14  10         251    $7,362,155
29        R Moore    2    5    1   0   4          21   $12,818,503
30      R Bayliss    2    3    4   2   5          90    $3,181,375
31    C Soumillon    1    1    0   1   0           4   $19,620,000
32     M Matsuoka    1    0    0   0   0           1   $15,960,000
33        C Keane    1    0    0   0   0           4      $991,800
34       H Bowman    0    3    1   5   2          18    $5,491,445
35     J McDonald    0    2    0   2   0          13      $943,420
36       Y Kawada    0    1    0   1   0           4      $324,912
37      J Spencer    0    1    0   0   1           8    $2,233,845
38       O Murphy    0    0    1   3   2          11    $2,393,645
39         D Lane    0    0    0   1   0           3       $87,000
40         W L Ho    0    0    0   1   0           3      $195,000
41      C Lemaire    0    0    0   1   0           5    $1,425,000
42        M Guyon    0    0    0   0   2           3      $710,750
43     S Pasquier    0    0    0   0   1           1      $924,000
44      L Dettori    0    0    0   0   1           8       $40,614
45      B Avdulla    0    0    0   0   0           1            $0
46       J Watson    0    0    0   0   0           1            $0
47       K McEvoy    0    0    0   0   0           1            $0
48       M Walker    0    0    0   0   0           1            $0
49       W Lordan    0    0    0   0   0           1            $0
50     P-C Boudot    0    0    0   0   0           4            $0

In [ ]:
jockeyframe.to_csv('jockeys.csv',index=False)