In [1]:
#!pip install pandasql
import pandas as pd
import pandasql as ps
from matplotlib import pyplot as plt
import numpy as np
import seaborn as sns

In [2]:
import pandas
jockeys=pandas.read_csv('./data/jockeys.csv')
jockeyspercent=pandas.read_csv(r'./data/jockeys_pct.csv')
trainers=pandas.read_csv('./data/trainers.csv')
trainerspercent=pandas.read_csv(r'./data/trainers_pct.csv')
horsesprofiles=pandas.read_csv('./data/horses.csv')
main=pandas.read_csv('./data/full_season_performance_clean.csv')
pd.options.display.max_columns = None   #display all columns in jupyter
horsesprofiles.columns=['H_id', 'H_name', 'H_country', 'H_age', 'H_colour', 'H_sex', 'H_ImportType', 'H_season_stakes', 'H_ttl_stakes', 'H_no_of_1_2_3_Starts', 'H_no_of_starts_in_past10', 'H_curr_location', 'H_arr_date', 'H_trainer', 'H_owner', 'H_curr_rating', 'H_1920rating', 'H_sire', 'H_dam', 'H_damSire']
#main['horse_id']=main['horse'].apply(lambda x: x[-5:-1])

In [3]:
main.head()

,race_id,race,date,place,horse_id,horse_no,horse,jockey,trainer,actual_weight,declared_horse_weight,draw,lbw,running_position,win_odds,class,going,track,prize,location,distance_m,finish_time,finish_time_s
0,1,1,2019-09-01 00:00:00.000,1,C127,3,GOOD RUNNERS WAY,Z Purton,C S Shum,131.0,1072.0,6,0.00,"['3', '3', '2', '1']",2.2,Class 5,GOOD,"TURF - ""B"" Course",725000,Sha Tin,1600,1900-01-01 00:01:35.480,95.48
1,1,1,2019-09-01 00:00:00.000,2,C035,4,REGENCY GEM,J Moreira,W Y So,129.0,1179.0,7,0.10,"['9', '8', '8', '2']",4.9,Class 5,GOOD,"TURF - ""B"" Course",725000,Sha Tin,1600,1900-01-01 00:01:35.500,95.50
2,1,1,2019-09-01 00:00:00.000,3,V406,7,PROUD SKY,K Teetan,L Ho,121.0,1053.0,4,0.50,"['5', '4', '3', '3']",18.0,Class 5,GOOD,"TURF - ""B"" Course",725000,Sha Tin,1600,1900-01-01 00:01:35.570,95.57
3,1,1,2019-09-01 00:00:00.000,4,V369,2,LE PANACHE,A Sanna,D J Whyte,132.0,1076.0,3,1.25,"['4', '6', '6', '4']",5.7,Class 5,GOOD,"TURF - ""B"" Course",725000,Sha Tin,1600,1900-01-01 00:01:35.680,95.68
4,1,1,2019-09-01 00:00:00.000,5,V400,1,GOLD VELVET,L Hewitson,A T Millard,133.0,1155.0,8,1.50,"['8', '7', '7', '5']",7.0,Class 5,GOOD,"TURF - ""B"" Course",725000,Sha Tin,1600,1900-01-01 00:01:35.710,95.71

In [4]:
main1=ps.sqldf('''
select a.* , --main table

--add Jockey Infor
b.Win as J_Win, c.Win as J_Win_perc, 
b.'2nd' as J_2nd,  c.'2nd' as J_2nd_perc,
b.'3rd' as J_3rd,  c.'3rd' as J_3rd_perc,
b.'4th' as J_4th,  c.'4th' as J_4th_perc,
b.'5th' as J_5th,  c.'5th' as J_5th_perc,

--add Trainers Infor
b.'Total Rides' as J_ttl_rides, c.'Stakes Won' as J_stakes_won,
d.Win as T_Win, e.Win as T_Win_perc,
d.'2nd' as T_2nd,  e.'2nd' as T_2nd_perc,
d.'3rd' as T_3rd,  e.'3rd' as T_3rd_perc,
d.'4th' as T_4th,  e.'4th' as T_4th_perc,
d.'5th' as T_5th,  e.'5th' as T_5th_perc,
d.'Total Runs' as T_ttl_runs, e.'Stakes Won' as T_stakes_won,

--add Horse Infor
f.*

from main a 
left join jockeys b on a.jockey=b.Jockey
left join jockeyspercent c on a.jockey=c.Jockey
left join trainers d on a.trainer=d.Trainer
left join trainerspercent e on a.trainer=e.Trainer
left join horsesprofiles f on a.horse_id=f.H_id
''')

In [5]:
main1.head()

,race_id,race,date,place,horse_id,horse_no,horse,jockey,trainer,actual_weight,declared_horse_weight,draw,lbw,running_position,win_odds,class,going,track,prize,location,distance_m,finish_time,finish_time_s,J_Win,J_Win_perc,J_2nd,J_2nd_perc,J_3rd,J_3rd_perc,J_4th,J_4th_perc,J_5th,J_5th_perc,J_ttl_rides,J_stakes_won,T_Win,T_Win_perc,T_2nd,T_2nd_perc,T_3rd,T_3rd_perc,T_4th,T_4th_perc,T_5th,T_5th_perc,T_ttl_runs,T_stakes_won,H_id,H_name,H_country,H_age,H_colour,H_sex,H_ImportType,H_season_stakes,H_ttl_stakes,H_no_of_1_2_3_Starts,H_no_of_starts_in_past10,H_curr_location,H_arr_date,H_trainer,H_owner,H_curr_rating,H_1920rating,H_sire,H_dam,H_damSire
0,1,1,2019-09-01 00:00:00.000,1,C127,3,GOOD RUNNERS WAY,Z Purton,C S Shum,131.0,1072.0,6,0.00,"['3', '3', '2', '1']",2.2,Class 5,GOOD,"TURF - ""B"" Course",725000,Sha Tin,1600,1900-01-01 00:01:35.480,95.48,147,21%,101,14%,100,14%,56,8%,66,9%,707,"$202,112,646",45,9%,49,10%,26,5%,39,8%,43,9%,475,"$69,711,815",C127,GOOD RUNNERS WAY,NZ,6.0,Bay,Gelding,PPG,0.0,1388520.0,"['2', '1', '2', '22']",0.0,Conghua,2020-03-04,C S Shum,Mr & Mrs Peter Chan On Tak and Robert Chan Chi...,34.0,34.0,Battle Paint,Ysa Post,Postponed
1,1,1,2019-09-01 00:00:00.000,2,C035,4,REGENCY GEM,J Moreira,W Y So,129.0,1179.0,7,0.10,"['9', '8', '8', '2']",4.9,Class 5,GOOD,"TURF - ""B"" Course",725000,Sha Tin,1600,1900-01-01 00:01:35.500,95.50,138,19%,123,17%,91,13%,68,9%,66,9%,719,"$206,911,366",31,7%,28,7%,33,8%,33,8%,28,7%,426,"$35,330,615",C035,REGENCY GEM,NZ,6.0,Bay,Gelding,PPG,0.0,1016240.0,"['1', '2', '2', '19']",0.0,Hong Kong,2020-07-02,W Y So,Wendy Wong Yin Ting & Owen Cheng Ho Wang,40.0,40.0,Showcasing,The Myth,Cape Cross
2,1,1,2019-09-01 00:00:00.000,3,V406,7,PROUD SKY,K Teetan,L Ho,121.0,1053.0,4,0.50,"['5', '4', '3', '3']",18.0,Class 5,GOOD,"TURF - ""B"" Course",725000,Sha Tin,1600,1900-01-01 00:01:35.570,95.57,93,13%,75,10%,81,11%,81,11%,72,10%,719,"$138,503,489",15,4%,28,7%,17,4%,36,8%,20,5%,427,"$21,136,215",V406,PROUD SKY,GB,7.0,Bay,Gelding,PP,0.0,1780625.0,"['3', '0', '1', '42']",0.0,Hong Kong,2016-06-25,L Ho,Francis Wong Shing Yick & Raymond Wong Kai Yuen,24.0,24.0,Acclamation,Claiomh Solais,Galileo
3,1,1,2019-09-01 00:00:00.000,4,V369,2,LE PANACHE,A Sanna,D J Whyte,132.0,1076.0,3,1.25,"['4', '6', '6', '4']",5.7,Class 5,GOOD,"TURF - ""B"" Course",725000,Sha Tin,1600,1900-01-01 00:01:35.680,95.68,9,8%,4,3%,9,8%,7,6%,10,8%,120,"$10,735,300",44,9%,41,9%,38,8%,47,10%,40,9%,466,"$51,039,432",V369,LE PANACHE,IRE,NaN,Bay,Gelding,PP,NaN,2501500.0,"['2', '6', '5', '42']",0.0,None,None,None,Kok Jian Pei,NaN,38.0,Acclamation,Heavens Peak,Pivotal
4,1,1,2019-09-01 00:00:00.000,5,V400,1,GOLD VELVET,L Hewitson,A T Millard,133.0,1155.0,8,1.50,"['8', '7', '7', '5']",7.0,Class 5,GOOD,"TURF - ""B"" Course",725000,Sha Tin,1600,1900-01-01 00:01:35.710,95.71,3,1%,9,4%,11,4%,14,6%,10,4%,251,"$7,362,155",30,9%,28,8%,33,10%,23,7%,25,7%,346,"$37,234,605",V400,GOLD VELVET,NZ,NaN,Bay / Brown,Gelding,PPG,NaN,2005145.0,"['2', '4', '3', '34']",0.0,None,None,None,"Gibson Lau Wai Chi, Eric Lau Pui Kit & Ricky L...",NaN,42.0,Savabeel,Girls On Top,O'Reilly

In [6]:
#clean str other than no.
main1['J_Win_perc']=main1['J_Win_perc'].str.strip('%')
main1['J_2nd_perc']=main1['J_2nd_perc'].str.strip('%')
main1['J_3rd_perc']=main1['J_3rd_perc'].str.strip('%')
main1['J_4th_perc']=main1['J_4th_perc'].str.strip('%')
main1['J_5th_perc']=main1['J_5th_perc'].str.strip('%')
main1['J_stakes_won']=main1['J_stakes_won'].str.strip('$')

main1['T_Win_perc']=main1['T_Win_perc'].str.strip('%')
main1['T_2nd_perc']=main1['T_2nd_perc'].str.strip('%')
main1['T_3rd_perc']=main1['T_3rd_perc'].str.strip('%')
main1['T_4th_perc']=main1['T_4th_perc'].str.strip('%')
main1['T_5th_perc']=main1['T_5th_perc'].str.strip('%')
main1['T_stakes_won']=main1['T_stakes_won'].str.strip('$')

#main1['H_season_stakes']=main1['H_season_stakes'].str.strip('$')
#main1['H_ttl_stakes']=main1['H_ttl_stakes'].str.strip('$')

In [7]:
main1.head()

,race_id,race,date,place,horse_id,horse_no,horse,jockey,trainer,actual_weight,declared_horse_weight,draw,lbw,running_position,win_odds,class,going,track,prize,location,distance_m,finish_time,finish_time_s,J_Win,J_Win_perc,J_2nd,J_2nd_perc,J_3rd,J_3rd_perc,J_4th,J_4th_perc,J_5th,J_5th_perc,J_ttl_rides,J_stakes_won,T_Win,T_Win_perc,T_2nd,T_2nd_perc,T_3rd,T_3rd_perc,T_4th,T_4th_perc,T_5th,T_5th_perc,T_ttl_runs,T_stakes_won,H_id,H_name,H_country,H_age,H_colour,H_sex,H_ImportType,H_season_stakes,H_ttl_stakes,H_no_of_1_2_3_Starts,H_no_of_starts_in_past10,H_curr_location,H_arr_date,H_trainer,H_owner,H_curr_rating,H_1920rating,H_sire,H_dam,H_damSire
0,1,1,2019-09-01 00:00:00.000,1,C127,3,GOOD RUNNERS WAY,Z Purton,C S Shum,131.0,1072.0,6,0.00,"['3', '3', '2', '1']",2.2,Class 5,GOOD,"TURF - ""B"" Course",725000,Sha Tin,1600,1900-01-01 00:01:35.480,95.48,147,21,101,14,100,14,56,8,66,9,707,"202,112,646",45,9,49,10,26,5,39,8,43,9,475,"69,711,815",C127,GOOD RUNNERS WAY,NZ,6.0,Bay,Gelding,PPG,0.0,1388520.0,"['2', '1', '2', '22']",0.0,Conghua,2020-03-04,C S Shum,Mr & Mrs Peter Chan On Tak and Robert Chan Chi...,34.0,34.0,Battle Paint,Ysa Post,Postponed
1,1,1,2019-09-01 00:00:00.000,2,C035,4,REGENCY GEM,J Moreira,W Y So,129.0,1179.0,7,0.10,"['9', '8', '8', '2']",4.9,Class 5,GOOD,"TURF - ""B"" Course",725000,Sha Tin,1600,1900-01-01 00:01:35.500,95.50,138,19,123,17,91,13,68,9,66,9,719,"206,911,366",31,7,28,7,33,8,33,8,28,7,426,"35,330,615",C035,REGENCY GEM,NZ,6.0,Bay,Gelding,PPG,0.0,1016240.0,"['1', '2', '2', '19']",0.0,Hong Kong,2020-07-02,W Y So,Wendy Wong Yin Ting & Owen Cheng Ho Wang,40.0,40.0,Showcasing,The Myth,Cape Cross
2,1,1,2019-09-01 00:00:00.000,3,V406,7,PROUD SKY,K Teetan,L Ho,121.0,1053.0,4,0.50,"['5', '4', '3', '3']",18.0,Class 5,GOOD,"TURF - ""B"" Course",725000,Sha Tin,1600,1900-01-01 00:01:35.570,95.57,93,13,75,10,81,11,81,11,72,10,719,"138,503,489",15,4,28,7,17,4,36,8,20,5,427,"21,136,215",V406,PROUD SKY,GB,7.0,Bay,Gelding,PP,0.0,1780625.0,"['3', '0', '1', '42']",0.0,Hong Kong,2016-06-25,L Ho,Francis Wong Shing Yick & Raymond Wong Kai Yuen,24.0,24.0,Acclamation,Claiomh Solais,Galileo
3,1,1,2019-09-01 00:00:00.000,4,V369,2,LE PANACHE,A Sanna,D J Whyte,132.0,1076.0,3,1.25,"['4', '6', '6', '4']",5.7,Class 5,GOOD,"TURF - ""B"" Course",725000,Sha Tin,1600,1900-01-01 00:01:35.680,95.68,9,8,4,3,9,8,7,6,10,8,120,"10,735,300",44,9,41,9,38,8,47,10,40,9,466,"51,039,432",V369,LE PANACHE,IRE,NaN,Bay,Gelding,PP,NaN,2501500.0,"['2', '6', '5', '42']",0.0,None,None,None,Kok Jian Pei,NaN,38.0,Acclamation,Heavens Peak,Pivotal
4,1,1,2019-09-01 00:00:00.000,5,V400,1,GOLD VELVET,L Hewitson,A T Millard,133.0,1155.0,8,1.50,"['8', '7', '7', '5']",7.0,Class 5,GOOD,"TURF - ""B"" Course",725000,Sha Tin,1600,1900-01-01 00:01:35.710,95.71,3,1,9,4,11,4,14,6,10,4,251,"7,362,155",30,9,28,8,33,10,23,7,25,7,346,"37,234,605",V400,GOLD VELVET,NZ,NaN,Bay / Brown,Gelding,PPG,NaN,2005145.0,"['2', '4', '3', '34']",0.0,None,None,None,"Gibson Lau Wai Chi, Eric Lau Pui Kit & Ricky L...",NaN,42.0,Savabeel,Girls On Top,O'Reilly

In [8]:
#pd.options.display.max_rows = None   #display all rows in jupyter
pd.reset_option('display.max_rows') #reset
main1.dtypes

race_id            int64
race               int64
date              object
place              int64
horse_id          object
                  ...
H_curr_rating    float64
H_1920rating     float64
H_sire            object
H_dam             object
H_damSire         object
Length: 67, dtype: object

In [9]:
main1.to_csv('Performance left join jockey and trainers and horse infor.csv')